mkdir "C:\Users\Public\Desktop\Eletrobras"
move /y "C:\Users\Public\Desktop\Anafas 7.2.7.lnk" "C:\Users\Public\Desktop\Eletrobras"
move /y "C:\Users\Public\Desktop\Anafas DOS 7.2.7.lnk" "C:\Users\Public\Desktop\Eletrobras"
move /y "C:\Users\Public\Desktop\Anarede 11.3.1.lnk" "C:\Users\Public\Desktop\Eletrobras"
move /y "C:\Users\Public\Desktop\Anatem 11.8.1.lnk" "C:\Users\Public\Desktop\Eletrobras"
move /y "C:\Users\Public\Desktop\CduEdit 2.1.0.lnk" "C:\Users\Public\Desktop\Eletrobras"
move /y "C:\Users\Public\Desktop\EditCepel 1.4.26.lnk" "C:\Users\Public\Desktop\Eletrobras"
move /y "C:\Users\Public\Desktop\Flupot 7.7.0.lnk" "C:\Users\Public\Desktop\Eletrobras"
move /y "C:\Users\Public\Desktop\FormCepel 1.6.21.lnk" "C:\Users\Public\Desktop\Eletrobras"
move /y "C:\Users\Public\Desktop\HarmZs 3.6.1.lnk" "C:\Users\Public\Desktop\Eletrobras"
move /y "C:\Users\Public\Desktop\PacDyn9.9.9.lnk" "C:\Users\Public\Desktop\Eletrobras"
move /y "C:\Users\Public\Desktop\PlotCepel 5.0.3.lnk" "C:\Users\Public\Desktop\Eletrobras"
xcopy "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\NH2.lnk" "C:\Users\Public\Desktop\Eletrobras" /y