Reg.exe add "HKLM\SOFTWARE\WOW6432Node\CST AG\CST DESIGN ENVIRONMENT\2022" /v "SYSTEM_ID" /t REG_SZ /d "AMD64" /f
Reg.exe add "HKLM\SOFTWARE\WOW6432Node\CST AG\CST DESIGN ENVIRONMENT\2022" /v "LICENSEMODE" /t REG_SZ /d "FLEXNET" /f
Reg.exe add "HKLM\SOFTWARE\WOW6432Node\CST AG\CST DESIGN ENVIRONMENT\2022" /v "LICENSESERVER_DSLS" /t REG_SZ /d "" /f
Reg.exe add "HKLM\SOFTWARE\WOW6432Node\CST AG\CST DESIGN ENVIRONMENT\2022" /v "INSTALLPATH" /t REG_SZ /d "C:\Program Files (x86)\CST Studio Suite 2022\\" /f
Reg.exe add "HKLM\SOFTWARE\WOW6432Node\CST AG\CST DESIGN ENVIRONMENT\2022" /v "LICENSESERVER" /t REG_SZ /d "27000@10.40.48.92" /f
Reg.exe add "HKLM\SOFTWARE\WOW6432Node\CST AG\CST DESIGN ENVIRONMENT\2022" /v "AUTO_UPDATE_PROXY_PASSWORD" /t REG_SZ /d "" /f
Reg.exe add "HKLM\SOFTWARE\WOW6432Node\CST AG\CST DESIGN ENVIRONMENT\2022" /v "AUTO_UPDATE_PROXY_USERNAME" /t REG_SZ /d "" /f
Reg.exe add "HKLM\SOFTWARE\WOW6432Node\CST AG\CST DESIGN ENVIRONMENT\2022" /v "AUTO_UPDATE_PATH" /t REG_SZ /d "" /f
Reg.exe add "HKLM\SOFTWARE\WOW6432Node\CST AG\CST DESIGN ENVIRONMENT\2022" /v "AUTO_UPDATE_LOGIN_USERNAME" /t REG_SZ /d "" /f
Reg.exe add "HKLM\SOFTWARE\WOW6432Node\CST AG\CST DESIGN ENVIRONMENT\2022" /v "AUTO_UPDATE_LOGIN_PASSWORD" /t REG_SZ /d "" /f
Reg.exe add "HKLM\SOFTWARE\WOW6432Node\CST AG\CST DESIGN ENVIRONMENT\2022" /v "AUTO_UPDATE_ACTIVE" /t REG_SZ /d "INTERNET" /f