mkdir "C:\Users\Public\Desktop\Adobe 2024"
mklink "C:\Users\Public\Desktop\Adobe 2024\Adobe After Effects 2024" "C:\Program Files\Adobe\Adobe After Effects 2024\Support Files\AfterFX.exe"
mklink "C:\Users\Public\Desktop\Adobe 2024\Adobe Audition 2024" "C:\Program Files\Adobe\Adobe Audition 2024\Adobe Audition.exe"
mklink "C:\Users\Public\Desktop\Adobe 2024\Adobe Bridge 2024" "C:\Program Files\Adobe\Adobe Bridge 2024\Adobe Bridge.exe"
mklink "C:\Users\Public\Desktop\Adobe 2024\Adobe Creative Cloud" "C:\Program Files\Adobe\Adobe Creative Cloud\ACC\Creative Cloud.exe"
mklink "C:\Users\Public\Desktop\Adobe 2024\Adobe Dreamweaver 2021" "C:\Program Files\Adobe\Adobe Dreamweaver 2021\Dreamweaver.exe"
mklink "C:\Users\Public\Desktop\Adobe 2024\Adobe Illustrator 2024" "C:\Program Files\Adobe\Adobe Illustrator 2024\Support Files\Contents\Windows\Illustrator.exe"
mklink "C:\Users\Public\Desktop\Adobe 2024\Adobe InDesign 2024" "C:\Program Files\Adobe\Adobe InDesign 2024\InDesign.exe"
mklink "C:\Users\Public\Desktop\Adobe 2024\Adobe Lightroom Classic""C:\Program Files\Adobe\Adobe Lightroom Classic\Lightroom.exe"
mklink "C:\Users\Public\Desktop\Adobe 2024\Adobe Media Encoder 2024" "C:\Program Files\Adobe\Adobe Media Encoder 2024\Adobe Media Encoder.exe"
mklink "C:\Users\Public\Desktop\Adobe 2024\Adobe Photoshop 2024" "C:\Program Files\Adobe\Adobe Photoshop 2024\Photoshop.exe"
mklink "C:\Users\Public\Desktop\Adobe 2024\Adobe Premiere Pro 2024" "C:\Program Files\Adobe\Adobe Premiere Pro 2024\Adobe Premiere Pro.exe"
mkdir "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Adobe 2024"
move "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Adobe After Effects 2024.lnk" "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Adobe 2024"
move "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Adobe Audition 2024.lnk" "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Adobe 2024"
move "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Adobe Bridge 2024.lnk" "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Adobe 2024"
move "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Adobe Creative Cloud.lnk" "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Adobe 2024"
move "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Adobe Dreamweaver 2021.lnk" "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Adobe 2024"
move "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Adobe Illustrator 2024.lnk" "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Adobe 2024"
move "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Adobe InDesign 2024.lnk" "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Adobe 2024"
move "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Adobe Lightroom Classic.lnk" "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Adobe 2024"
move "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Adobe Media Encoder 2024.lnk" "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Adobe 2024"
move "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Adobe Photoshop 2024.lnk" "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Adobe 2024"
move "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Adobe Premiere Pro 2024.lnk" "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Adobe 2024"