tar -xf "Y:\Applications\Reatores Quimicos\setup.zip" -C "C:\Program Files"
mkdir "C:\Users\Public\Desktop\Reatores Quimicos"
mklink "C:\Users\Public\Desktop\Reatores Quimicos\Ecology" "C:\Program Files\Reatores Quimicos\Ecology\Ecology.exe"
mklink "C:\Users\Public\Desktop\Reatores Quimicos\EnzymeMan" "C:\Program Files\Reatores Quimicos\EnzymeMan\EnzymeMan.exe"
mklink "C:\Users\Public\Desktop\Reatores Quimicos\Great Race" "C:\Program Files\Reatores Quimicos\Great Race\Great Race.exe"
mklink "C:\Users\Public\Desktop\Reatores Quimicos\Heat Effects I" "C:\Program Files\Reatores Quimicos\Heat Effects I\Heat Effects I.exe"
mklink "C:\Users\Public\Desktop\Reatores Quimicos\Heat Effects II" "C:\Program Files\Reatores Quimicos\Heat Effects II\Heat Effects II.exe"
mklink "C:\Users\Public\Desktop\Reatores Quimicos\Heterogeneous Catalysis" "C:\Program Files\Reatores Quimicos\Heterogeneous Catalysis\Heterogeneous Catalysis.exe"
mklink "C:\Users\Public\Desktop\Reatores Quimicos\Kinetic Challenge I" "C:\Program Files\Reatores Quimicos\Kinetic Challenge I\Kinetic Challenge I.exe"
mklink "C:\Users\Public\Desktop\Reatores Quimicos\Kinetic Challenge II" "C:\Program Files\Reatores Quimicos\Kinetic Challenge II\Kinetic Challenge II.exe"
mklink "C:\Users\Public\Desktop\Reatores Quimicos\MicroPlant" "C:\Program Files\Reatores Quimicos\MicroPlant\MicroPlant.exe"
mklink "C:\Users\Public\Desktop\Reatores Quimicos\Murder Mystery" "C:\Program Files\Reatores Quimicos\Murder Mystery\Murder Mystery.exe"
mklink "C:\Users\Public\Desktop\Reatores Quimicos\Staging" "C:\Program Files\Reatores Quimicos\Staging\Staging.exe"
mklink "C:\Users\Public\Desktop\Reatores Quimicos\Tic Tac Toe" "C:\Program Files\Reatores Quimicos\Tic Tac Toe\Tic Tac Toe.exe"